/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  docs: [
    {
      type: 'doc',
      id: 'introduction',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Quick Start',
          link: {
            type: 'doc',
            id: 'getting-started/quick-start',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'getting-started/quick-start',
            },
          ],
        },
        {
          type: 'category',
          label: 'Installation',
          items: ['getting-started/installation/helm-charts', 'getting-started/installation/binaries'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Integrations',
          items: [
            {
              type: 'category',
              label: 'Container Runtime',
              items: [
                'operations/integrations/container-runtime/containerd',
                {
                  type: 'category',
                  label: 'Singularity/Apptainer',
                  link: {
                    type: 'doc',
                    id: 'operations/integrations/container-runtime/singularity',
                  },
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'operations/integrations/container-runtime/singularity',
                    },
                  ],
                },
                'operations/integrations/container-runtime/docker',
                'operations/integrations/container-runtime/cri-o',
                'operations/integrations/container-runtime/nydus',
                'operations/integrations/container-runtime/stargz',
              ],
            },
            'operations/integrations/harbor',
            'operations/integrations/hugging-face',
            'operations/integrations/git-lfs',
            'operations/integrations/torchserve',
            'operations/integrations/triton-server',
            'operations/integrations/upgrade',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Terminology',
          items: [
            {
              type: 'autogenerated',
              dirName: 'concepts/terminology',
            },
          ],
        },
        {
          type: 'category',
          label: 'Observability',
          items: [
            {
              type: 'autogenerated',
              dirName: 'concepts/observability',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Configuration',
          items: [
            {
              type: 'autogenerated',
              dirName: 'reference/configuration',
            },
          ],
        },
        {
          type: 'category',
          label: 'Commands',
          items: [
            {
              type: 'category',
              label: 'Client',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'reference/commands/client',
                },
              ],
            },
            'reference/commands/manager',
            'reference/commands/scheduler',
          ],
        },
        'reference/personal-access-tokens',
        'reference/preheat',
        'reference/manage-console',
      ],
    },
    {
      type: 'category',
      label: 'Contribute',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Development Guide',
          items: [
            {
              type: 'autogenerated',
              dirName: 'contribute/development-guide',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Others',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'others',
        },
      ],
    },
  ],
};
