module.exports = {
  docs: [
    {
      type: 'doc',
      id: 'introduction',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Quick Start',
          link: {
            type: 'doc',
            id: 'getting-started/quick-start',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'getting-started/quick-start',
            },
          ],
        },
        {
          type: 'category',
          label: 'Installation',
          items: ['getting-started/installation/helm-charts', 'getting-started/installation/binaries'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Setup',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Runtime',
          items: [
            {
              type: 'category',
              label: 'Containerd',
              link: {
                type: 'doc',
                id: 'setup/runtime/containerd',
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'setup/runtime/containerd',
                },
              ],
            },
            {
              type: 'category',
              label: 'Singularity/Apptainer',
              link: {
                type: 'doc',
                id: 'setup/runtime/singularity',
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'setup/runtime/singularity',
                },
              ],
            },
            'setup/runtime/docker',
            'setup/runtime/cri-o',
          ],
        },
        {
          type: 'category',
          label: 'Integration',
          items: [
            {
              type: 'autogenerated',
              dirName: 'setup/integration',
            },
          ],
        },
        'setup/upgrade',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Terminology',
          items: [
            {
              type: 'autogenerated',
              dirName: 'concepts/terminology',
            },
          ],
        },
        {
          type: 'category',
          label: 'Observability',
          items: [
            {
              type: 'autogenerated',
              dirName: 'concepts/observability',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Configuration',
          items: [
            {
              type: 'autogenerated',
              dirName: 'reference/configuration',
            },
          ],
        },
        {
          type: 'category',
          label: 'Command Line',
          items: [
            {
              type: 'autogenerated',
              dirName: 'reference/cli',
            },
          ],
        },
        'reference/personal-access-tokens',
        'reference/preheat',
        'reference/manage-console',
      ],
    },
    {
      type: 'category',
      label: 'Contribute',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Development Guide',
          items: [
            {
              type: 'autogenerated',
              dirName: 'contribute/development-guide',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Others',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'others',
        },
      ],
    },
  ],
};
